### ISSUE TITLE
vaporize model ModelName

### ISSUE THREAD

**Issue by emilagervigstarup** [mcdappdev/vaporize#2]
vaporize model Item title:string imageUrl:string html:string isPrivate:bool isBusiness:bool

Does not generate NodeRepresentable and Field enum.

Do you know why? :)

**Comment by jdmcd** [comment]
Hi there! Sorry about my delayed response on this. When was the last time you installed the toolbox? Just for kicks, try this from your user folder on your mac:

`rm -rf /usr/local/bin/vaporize`
`rm -rf .vaporize`
`curl -sL 162llc.com/install.sh | bash`

Let me know if running that same command fixes the problem now :)

**Comment by emilagervigstarup** [comment]
`import Vapor
import FluentProvider

final class ModelName: Model {
    var storage = Storage()
    
    var property1: String
    var property2: Bool
    var property3: Int
    var property4: Double

    init(property1: String, property2: Bool, property3: Int, property4: Double) {
        self.property1 = property1
        self.property2 = property2
        self.property3 = property3
        self.property4 = property4
    }
    
    init(row: Row) throws {
        property1 = try row.get(ModelName.Field.property1)
        property2 = try row.get(ModelName.Field.property2)
        property3 = try row.get(ModelName.Field.property3)
        property4 = try row.get(ModelName.Field.property4)
    }

    init(json: JSON) throws {
        property1 = try json.get(ModelName.Field.property1)
        property2 = try json.get(ModelName.Field.property2)
        property3 = try json.get(ModelName.Field.property3)
        property4 = try json.get(ModelName.Field.property4)
    }
    
    func makeRow() throws -> Row {
        var row = Row()

        try row.set(ModelName.Field.property1, property1)
        try row.set(ModelName.Field.property2, property2)
        try row.set(ModelName.Field.property3, property3)
        try row.set(ModelName.Field.property4, property4)

        return row
    }
}

//MARK: - Preparation
extension ModelName: Preparation {
    static func prepare(_ database: Database) throws {
        try database.create(self, closure: { builder in
            builder.id()
            builder.string(ModelName.Field.property1)
            builder.bool(ModelName.Field.property2)
            builder.int(ModelName.Field.property3)
            builder.double(ModelName.Field.property4)
        })
    }
    
    static func revert(_ database: Database) throws {   
    }
}

//MARK: - JSONConvertible
extension ModelName: JSONConvertible {
    func makeJSON() throws -> JSON {
        var json = JSON()

        try json.set(ModelName.Field.id, id)
        try json.set(ModelName.Field.property1, property1)
        try json.set(ModelName.Field.property2, property2)
        try json.set(ModelName.Field.property3, property3)
        try json.set(ModelName.Field.property4, property4)
        try json.set(ModelName.createdAtKey, createdAt)
        try json.set(ModelName.updatedAtKey, updatedAt)

        return json
    }
}

//MARK: - Timestampable
extension ModelName: Timestampable { }

//MARK: - Field
extension ModelName {
    enum Field: String {
        case id
        case property1
        case property2
        case property3
        case property4
    }
}
`

Fields are showing up now, but not NodeRepresentable. :)

**Comment by jdmcd** [comment]
Oh shoot, I think I forgot to update the docs with the new output for Vapor 2. I removed the Node conformance. Would it be helpful if I added an option to the command like –node and –viewData which would add those functions?

**Comment by emilagervigstarup** [comment]
Yes would be great with the –node :)

**Comment by jdmcd** [comment]
@emilpedersen Would this be an acceptable solution?

``` swift
//MARK: - ViewDataRepresentable
extension Model: ViewDataRepresentable {
    func makeViewData() throws -> ViewData {
        return ViewData(try makeJSON())
    }
}

//MARK: - NodeRepresentable
extension Model: NodeRepresentable {
    func makeNode(in context: Context?) throws -> Node {
        return Node(try makeJSON())
    }
}
```

And those would only be added with the `--node` and `--viewData` flags?

**Comment by jdmcd** [comment]
@emilpedersen The docs have been updated to support that new feature: https://github.com/mcdappdev/vaporize#model
